version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    environment:
      - PORT=4000
      - MONGO_URI=${MONGO_URI}
      - ML_SERVER_URL=http://ml:8000
    ports:
      - "4000:4000"
    depends_on:
      - ml

  ml:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.ml
    environment:
      - MODEL_DIR=./models
    ports:
      - "8000:8000"
