export const levels = [
  {
    id:1,
    Level_no:"l1",
    page_title:"Mass Credential-Phish",
    Hint:"Phish email",
    js_path:"./levels/easy/l1.js",
    category:"easy",
    from_and_to:"Security/IT-Support team mail to the reciever",
    phish_email:"it-supp0rt@enphisim.com",
    crct_email:"it-support@enphisim.com",
    level_text:"Subject: Quick heads-up! Your account password is set to expire today. Please click this link right away to confirm your details and avoid losing access. - Your Friendly IT Team",
    subj:"Please Verify Your Account",
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Click Link",
    template_type:"mail"
  },
  {
    id:2,
    Level_no:"l2",
    page_title:"Scam Invoice/Payment reminder",
    Hint:"Phish email, wrong invoice and payment reminder",
    js_path:"./levels/easy/l2.js",
    category:"easy",
    from_and_to:"vendor to the supplier",
    phish_email:"it-supp0rt@enphisim.com",
    crct_email:"it-support@enphisim.com",
    level_text:"Subject: OVERDUE! We haven't received your payment of £200. Check the attached invoice and pay immediately to keep your service running! - Accounts Dept.",
    subj:"Your invoice from EnPhiSim",
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Open Attachment",
    template_type:"mail"
  },
  {
    id:3,
    Level_no:"l3",
    page_title:"Fake Newsletter Subscription",
    Hint:"Subscription confirmation is for a newsletter you don't recall joining.",
    js_path:"./levels/easy/l3.js",
    category:"easy",
    from_and_to:"marketing team to reciever",
    phish_email:"it-supp0rt@enphisim.com",
    crct_email:"it-support@enphisim.com",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Click Link",
    template_type:"mail"
  },
  {
    id:4,
    Level_no:"l4",
    page_title:"Lottery / Prize Scam",
    Hint:"Something is too good to be true.",
    js_path:"./levels/easy/l4.js",
    category:"easy",
    from_and_to:"scammer to the reciever",
    phish_email:"it-supp0rt@enphisim.com",
    crct_email:"it-support@enphisim.com",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Claim Prize",
    template_type:"mail"
  },
  {
    id:5,
    Level_no:"l5",
    page_title:"Simple attachment Lure",
    Hint:"Unexpected or suspicious file type",
    js_path:"./levels/easy/l5.js",
    category:"easy",
    from_and_to:"fake HR to reciever",
    phish_email:"it-supp0rt@enphisim.com",
    crct_email:"it-support@enphisim.com",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Open Attachment",
    template_type:"mail"
  },
  {
    id:6,
    Level_no:"l6",
    page_title:"Basic Spoofed display-name senders",
    Hint:"Mismatched Display Name and Address.",
    js_path:"./levels/easy/l6.js",
    category:"easy",
    from_and_to:"Fake sender to reciever",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Click Link",
    template_type:"mail"
  },
  {
    id:7,
    Level_no:"bl1",
    page_title:"Eagle",
    Hint:null,
    js_path:"./levels/easy/bl1.js",
    category:"easy",
    from_and_to:"Facts of eagle and Technology",
    level_text:null,
    correct_option:"Next",
    neutral_option:"Skip",
    wrong_option:"Download Image",
    template_type:"image"
  },
  {
    id:8,
    Level_no:"l7",
    page_title:"TypoSquatted Domain Phish",
    Hint:"Check the full email address, not just the name.",
    js_path:"./levels/advanced_easy/l7.js",
    category:"advanced_easy",
    from_and_to:"Fake domain to the user",
    level_text:null,
    correct_option:"Close Page",
    neutral_option:"Do Nothing",
    wrong_option:"Enter Details",
    template_type:"browser"
  },
  {
    id:9,
    Level_no:"l8",
    page_title:"URL Shortener Redirected Phish",
    Hint:"Links are deliberately obscured.",
    js_path:"./levels/advanced_easy/l8.js",
    category:"advanced_easy",
    from_and_to:"Fake redirection to the user",
    level_text:null,
    correct_option:"Close Page",
    neutral_option:"Do Nothing",
    wrong_option:"Proceed Anyway",
    template_type:"browser"
  },
  {
    id:10,
    Level_no:"l9",
    page_title:"Malicious survey / feedback request",
    Hint:"Survey asks for sensitive personal or security questions.",
    js_path:"./levels/advanced_easy/l9.js",
    category:"advanced_easy",
    from_and_to:"malicious feedback survey request to user",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Fill Survey",
    template_type:"mail"
  },
  {
    id:11,
    Level_no:"l10",
    page_title:"SMS (Smishing) generic link",
    Hint:"Unsolicited text message with a vague, urgent link.",
    js_path:"./levels/advanced_easy/l10.js",
    category:"advanced_easy",
    from_and_to:"Fake redirection msg to the user",
    level_text:null,
    correct_option:"Report SMS",
    neutral_option:"Ignore",
    wrong_option:"Tap Link",
    template_type:"message"
  },
  {
    id:12,
    Level_no:"l11",
    page_title:"Fake social media notification",
    Hint:"The link domain does not match the real platform.",
    js_path:"./levels/advanced_easy/l11.js",
    category:"advanced_easy",
    from_and_to:"pretending to have a notification to the user",
    level_text:null,
    correct_option:"Check Official App",
    neutral_option:"Dismiss",
    wrong_option:"Open Notification Link",
    template_type:"notification"
  },
  {
    id:13,
    Level_no:"l12",
    page_title:"Clone of a public service alert",
    Hint:"Unexpected government/tax/health fine notification.",
    js_path:"./levels/advanced_easy/l12.js",
    category:"advanced_easy",
    from_and_to:"duplication of the service",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Click Link",
    template_type:"mail"
  },
  {
    id:14,
    Level_no:"bl2",
    page_title:"Monkey",
    Hint:null,
    js_path:"./levels/advanced_easy/bl2.js",
    category:"advanced_easy",
    from_and_to:"Facts of monkey and Technology",
    level_text:null,
    correct_option:"Next",
    neutral_option:"Skip",
    wrong_option:"Download Image",
    template_type:"image"
  },
  {
    id:15,
    Level_no:"l13",
    page_title:"Spear-Phishing",
    Hint:"References internal projects or personal details.",
    js_path:"./levels/normal/l13.js",
    category:"normal",
    from_and_to:"Fake phishing to receiver",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Respond",
    template_type:"mail"
  },
  {
    id:16,
    Level_no:"l14",
    page_title:"Business Email Compromise",
    Hint:"Urgent financial request with a sudden change in procedure.",
    js_path:"./levels/normal/l14.js",
    category:"normal",
    from_and_to:"Fake redirection to the user",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Approve Payment",
    template_type:"mail"
  },
  {
    id:17,
    Level_no:"l15",
    page_title:"Drive / Share Notification",
    Hint:"Unexpected shared document from external source.",
    js_path:"./levels/normal/l15.js",
    category:"normal",
    from_and_to:"Fake redirection to the user",
    level_text:null,
    correct_option:"Open Drive Manually",
    neutral_option:"Ignore",
    wrong_option:"Open Shared Doc Link",
    template_type:"notification"
  },
  {
    id:18,
    Level_no:"l16",
    page_title:"Invoice Impersonation",
    Hint:"Unknown service or changed bank details.",
    js_path:"./levels/normal/l16.js",
    category:"normal",
    from_and_to:"pretending to be real invoice",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Pay Invoice",
    template_type:"mail"
  },
  {
    id:19,
    Level_no:"l17",
    page_title:"Account Lockout Scare",
    Hint:"Extreme urgency to force quick action.",
    js_path:"./levels/normal/l17.js",
    category:"normal",
    from_and_to:"Fake redirection to the user",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Restore Account",
    template_type:"mail"
  },
  {
    id:20,
    Level_no:"l18",
    page_title:"Credential-harvest via landing page",
    Hint:"Hover over the link before clicking.",
    js_path:"./levels/normal/l18.js",
    category:"normal",
    from_and_to:"fake landing page",
    level_text:null,
    correct_option:"Close Page",
    neutral_option:"Do Nothing",
    wrong_option:"Login",
    template_type:"browser"
  },
  {
    id:21,
    Level_no:"bl3",
    page_title:"Turtle",
    Hint:null,
    js_path:"./levels/normal/bl3.js",
    category:"normal",
    from_and_to:"Facts of turtle and Technology",
    level_text:null,
    correct_option:"Next",
    neutral_option:"Skip",
    wrong_option:"Download Image",
    template_type:"image"
  }
];
