export const levels = [
  {
    id:1,
    Level_no:"l1",
    page_title:"Mass Credential-Phish",
    Hint:"Phish email",
    js_path:"./levels/easy/l1.js",
    category:"easy",
    from_and_to:"Security/IT-Support team mail to the reciever",
    phish_email:"it-supp0rt@enphisim.com",
    crct_email:"it-support@enphisim.com",
    level_text:" Quick heads-up! Your account password is set to expire today. Please click this link right away to confirm your details and avoid losing access. - Your Friendly IT Team",
    subj:"Please Verify Your Account",
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Click Link",
    template_type:"mail"
  },
  {
    id:2,
    Level_no:"l2",
    page_title:"Scam Invoice/Payment reminder",
    Hint:"Phish email, wrong invoice and payment reminder",
    js_path:"./levels/easy/l2.js",
    category:"easy",
    from_and_to:"vendor to the supplier",
    phish_email:"it-supp0rt@enphisim.com",
    crct_email:"it-support@enphisim.com",
    level_text:" OVERDUE! We haven't received your payment of £200. Check the attached invoice and pay immediately to keep your service running! - Accounts Dept.",
    subj:"Your invoice from EnPhiSim",
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Open Attachment",
    template_type:"mail"
  },
  {
    id:3,
    Level_no:"l3",
    page_title:"Fake Newsletter Subscription",
    Hint:"Subscription confirmation is for a newsletter you don't recall joining.",
    js_path:"./levels/easy/l3.js",
    category:"easy",
    from_and_to:"marketing team to reciever",
    phish_e:"it-supp0rt@enphisim.com",
    crct_e:"it-support@enphisim.com",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Click Link",
    template_type:"mail"
  },
  {
    id:4,
    Level_no:"l4",
    page_title:"Lottery / Prize Scam",
    Hint:"Something is too good to be true.",
    js_path:"./levels/easy/l4.js",
    category:"easy",
    from_and_to:"scammer to the reciever",
    phish_e:"it-supp0rt@enphisim.com",
    crct_e:"it-support@enphisim.com",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Claim Prize",
    template_type:"mail"
  },
  {
    id:5,
    Level_no:"l5",
    page_title:"Simple attachment Lure",
    Hint:"Unexpected or suspicious file type",
    js_path:"./levels/easy/l5.js",
    category:"easy",
    from_and_to:"fake HR to reciever",
    phish_e:"it-supp0rt@enphisim.com",
    crct_e:"it-support@enphisim.com",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Open Attachment",
    template_type:"mail"
  },
  {
    id:6,
    Level_no:"l6",
    page_title:"Basic Spoofed display-name senders",
    Hint:"Mismatched Display Name and Address.",
    js_path:"./levels/easy/l6.js",
    category:"easy",
    from_and_to:"Fake sender to reciever",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Click Link",
    template_type:""
  },
  {
    id:7,
    Level_no:"bl1",
    page_title:"Eagle",
    Hint:null,
    js_path:"./levels/easy/bl1.js",
    category:"easy",
    from_and_to:"Facts of eagle and Technology",
    level_text:null,
    correct_option:"Next",
    neutral_option:"Skip",
    wrong_option:"Download Image",
    template_type:"image"
  },
  {
    id:8,
    Level_no:"l7",
    page_title:"TypoSquatted Domain Phish",
    Hint:"Check the full e address, not just the name.",
    js_path:"./levels/advanced_easy/l7.js",
    category:"advanced_easy",
    from_and_to:"Fake domain to the user",
    level_text:null,
    correct_option:"Close Page",
    neutral_option:"Do Nothing",
    wrong_option:"Enter Details",
    template_type:"browser"
  },
  {
    id:9,
    Level_no:"l8",
    page_title:"URL Shortener Redirected Phish",
    Hint:"Links are deliberately obscured.",
    js_path:"./levels/advanced_easy/l8.js",
    category:"advanced_easy",
    from_and_to:"Fake redirection to the user",
    level_text:null,
    correct_option:"Close Page",
    neutral_option:"Do Nothing",
    wrong_option:"Proceed Anyway",
    template_type:"browser"
  },
  {
    id:10,
    Level_no:"l9",
    page_title:"Malicious survey / feedback request",
    Hint:"Survey asks for sensitive personal or security questions.",
    js_path:"./levels/advanced_easy/l9.js",
    category:"advanced_easy",
    from_and_to:"malicious feedback survey request to user",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Fill Survey",
    template_type:"mail"
  },
  {
    id:11,
    Level_no:"l10",
    page_title:"SMS (Smishing) generic link",
    Hint:"Unsolicited text message with a vague, urgent link.",
    js_path:"./levels/advanced_easy/l10.js",
    category:"advanced_easy",
    from_and_to:"Fake redirection msg to the user",
    level_text:null,
    correct_option:"Report SMS",
    neutral_option:"Ignore",
    wrong_option:"Tap Link",
    template_type:"message"
  },
  {
    id:12,
    Level_no:"l11",
    page_title:"Fake social media notification",
    Hint:"The link domain does not match the real platform.",
    js_path:"./levels/advanced_easy/l11.js",
    category:"advanced_easy",
    from_and_to:"pretending to have a notification to the user",
    level_text:null,
    correct_option:"Check Official App",
    neutral_option:"Dismiss",
    wrong_option:"Open Notification Link",
    template_type:"notification"
  },
  {
    id:13,
    Level_no:"l12",
    page_title:"Clone of a public service alert",
    Hint:"Unexpected government/tax/health fine notification.",
    js_path:"./levels/advanced_easy/l12.js",
    category:"advanced_easy",
    from_and_to:"duplication of the service",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Click Link",
    template_type:"mail"
  },
  {
    id:14,
    Level_no:"bl2",
    page_title:"Monkey",
    Hint:null,
    js_path:"./levels/advanced_easy/bl2.js",
    category:"advanced_easy",
    from_and_to:"Facts of monkey and Technology",
    level_text:null,
    correct_option:"Next",
    neutral_option:"Skip",
    wrong_option:"Download Image",
    template_type:"image"
  },
  {
    id:15,
    Level_no:"l13",
    page_title:"Spear-Phishing",
    Hint:"References internal projects or personal details.",
    js_path:"./levels/normal/l13.js",
    category:"normal",
    from_and_to:"Fake phishing to receiver",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Respond",
    template_type:"mail"
  },
  {
    id:16,
    Level_no:"l14",
    page_title:"Business E Compromise",
    Hint:"Urgent financial request with a sudden change in procedure.",
    js_path:"./levels/normal/l14.js",
    category:"normal",
    from_and_to:"Fake redirection to the user",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Approve Payment",
    template_type:"mail"
  },
  {
    id:17,
    Level_no:"l15",
    page_title:"Drive / Share Notification",
    Hint:"Unexpected shared document from external source.",
    js_path:"./levels/normal/l15.js",
    category:"normal",
    from_and_to:"Fake redirection to the user",
    level_text:null,
    correct_option:"Open Drive Manually",
    neutral_option:"Ignore",
    wrong_option:"Open Shared Doc Link",
    template_type:"notification"
  },
  {
    id:18,
    Level_no:"l16",
    page_title:"Invoice Impersonation",
    Hint:"Unknown service or changed bank details.",
    js_path:"./levels/normal/l16.js",
    category:"normal",
    from_and_to:"pretending to be real invoice",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Pay Invoice",
    template_type:"mail"
  },
  {
    id:19,
    Level_no:"l17",
    page_title:"Account Lockout Scare",
    Hint:"Extreme urgency to force quick action.",
    js_path:"./levels/normal/l17.js",
    category:"normal",
    from_and_to:"Fake redirection to the user",
    level_text:null,
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Restore Account",
    template_type:"mail"
  },
  {
    id:20,
    Level_no:"l18",
    page_title:"Credential-harvest via landing page",
    Hint:"Hover over the link before clicking.",
    js_path:"./levels/normal/l18.js",
    category:"normal",
    from_and_to:"fake landing page",
    level_text:null,
    correct_option:"Close Page",
    neutral_option:"Do Nothing",
    wrong_option:"Login",
    template_type:"browser"
  },
  {
    id:21,
    Level_no:"bl3",
    page_title:"Turtle",
    Hint:null,
    js_path:"./levels/normal/bl3.js",
    category:"normal",
    from_and_to:"Facts of turtle and Technology",
    level_text:null,
    correct_option:"Next",
    neutral_option:"Skip",
    wrong_option:"Download Image",
    template_type:"image"
  },
  { id:22,
    Level_no:"l19", 
    page_title:"Whaling ", 
    Hint:"A high-level executive (C-suite) is pressured into an unusual, high-value financial or data request that demands secrecy.", 
    js_path:"./levels/pre_hard/l19.js", 
    category:"pre_hard", 
    from_and_to:"Facts of whaling and Technology", 
    level_text:null,     
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Click Link", 
    template_type:"mail" 
  },
  { id:23, 
    Level_no:"l20", 
    page_title:"spear+ vishing combo", 
    Hint:"An email sets the stage, and then a call follows up.", 
    js_path:"./levels/pre_hard/l20.js", 
    category:"pre_hard", 
    from_and_to:"Fake redirection to the user", 
    level_text:null, 
    correct_option:null, 
    neutral_option:null, 
    wrong_option:null, 
    template_type:"message" 
  }, 
  { id:24, 
    Level_no:"l21", 
    page_title:"Qrcode Quishing", 
    Hint:"Unsolicited QR codes.", 
    js_path:"./levels/pre_hard/l21.js", 
    category:"pre_hard", 
    from_and_to:"fake phish to the user with vishing", 
    level_text:null, 
    correct_option:null, 
    neutral_option:null, 
    wrong_option:null, 
    template_type:"poster" 
  }, 
  { id:25, 
    Level_no:"l22", 
    page_title:"Account takeover", 
    Hint:"Unexpected password reset, login notification, or small, unusual internal emails.", 
    js_path:"./levels/pre_hard/l22.js", 
    category:"pre_hard", 
    from_and_to:"fake qrcode redirection to the user", 
    level_text:null,     
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Click Link", 
    template_type:"mail + browser" 
  }, 
  { id:26, 
    Level_no:"l23", 
    page_title:"Malicious HTML or embedded script in attachment", 
    Hint:"Unusual file extensions like .html, .hta, or a seemingly harmless .docm with macros.", 
    js_path:"./levels/pre_hard/l23.js", 
    category:"pre_hard", 
    from_and_to:"html page with malicious html header", 
    level_text:null, 
    correct_option:null, 
    neutral_option:null, 
    wrong_option:null, 
    template_type:"browser" 
  }, 
  { id:27, 
    Level_no:"bl4", 
    page_title:"Shark", 
    Hint:null, 
    js_path:"./levels/pre_hard/bl4.js", 
    category:"pre-hard", 
    from_and_to:"Facts of shark and Technology", 
    level_text:null, 
    correct_option:null, 
    neutral_option:null, 
    wrong_option:null, 
    template_type:"image" 
  }, 
  { id:28, 
    Level_no:"l24", 
    page_title:"Business Process Commpromise", 
    Hint:"Unexpected changes to internal systems or processes that don't match formal approvals.", 
    js_path:"./levels/hard/l24.js", 
    category:"hard", 
    from_and_to:"Fake redirection to the user", 
    level_text:null,    
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Click Link",
    template_type:"mail" 
  }, 
  { id:29, 
    Level_no:"l25", 
    page_title:"Compromised internal Account Spear-phish", 
    Hint:"The email comes from a real colleague's address but contains uncharacteristic language or an unexpected request for a file or link.", 
    js_path:"./levels/hard/l25.js", 
    category:"hard", 
    from_and_to:"Fake Spear- to reciever", 
    level_text:null, 
    correct_option:null, 
    neutral_option:null, 
    wrong_option:null, 
    template_type:"mail + message" 
  }, 
  { id:30, 
    Level_no:"l26", 
    page_title:"Deepfake-assisted voice vishing", 
    Hint:"A familiar voice makes an unusual or high-pressure request over the phone.", 
    js_path:"./levels/hard/l26.js", 
    category:"hard", 
    from_and_to:"Fake vishin to reciever", 
    level_text:null, 
    correct_option:null, 
    neutral_option:null, 
    wrong_option:null, 
    template_type:"message" 
  }, 
  { id:31, 
    Level_no:"l27", 
    page_title:"man-in-the-middle credential capture", 
    Hint:"The login page has a vaidURL but asks for credentials too often.", 
    js_path:"./levels/hard/27.js", 
    category:"hard", 
    from_and_to:"Fake captur to reciever", 
    level_text:"null", 
    correct_option:null, 
    neutral_option:null,
    wrong_option:null, 
    template_type:"browser + mail" 
  }, 
  { id:32, 
    Level_no:"l28", 
    page_title:"Targeted supply-chain Phishing", 
    Hint:"An email comes from a legitimate, trusted third-party vendor about an unexpected software update.", 
    js_path:"./levels/hard/l28.js", 
    category:"hard", 
    from_and_to:"Fake Phishing mail to reciever", 
    level_text:null,     
    correct_option:"Report Phish",
    neutral_option:"Ignore",
    wrong_option:"Click Link", 
    template_type:"mail" 
  }, 
  { id:33, 
    Level_no:"bl5", 
    page_title:"Elephant", 
    Hint:null, 
    js_path:"./levels/hard/bl5.js", 
    category:"hard", 
    from_and_to:"Facts of elephant and Technology", 
    level_text:null, 
    correct_option:null, 
    neutral_option:null, 
    wrong_option:null, 
    template_type:"image" 
  }, 
  { id:34, 
    Level_no:"l29", 
    page_title:"AI-generated personalised campaigns", 
    Hint:"Hyper-realistic, perfect language and strong context.", 
    js_path:"./levels/advanced_hard/l29.js", 
    category:"advanced_hard", 
    from_and_to:"Fake campai to reciever", 
    level_text:null, 
    correct_option:null, 
    neutral_option:null, 
    wrong_option:null, 
    template_type:"mail + browser" 
  }, 
  { id:35, 
    Level_no:"l30", 
    page_title:"Homograph/unicode confusablle domain attacks", 
    Hint:"Characters lookidntical but are different.", 
    js_path:"./levels/advanced_hard/l30.js", 
    category:"advanced_hard", 
    from_and_to:"fake domain similar as the real domai ", 
    level_text:null, 
    correct_option:null, 
    neutral_option:null, 
    wrong_option:null, 
    template_type:"browser + message" 
  }, 
  { id:36, 
    Level_no:"l31", 
    page_title:"credential replay+ slow drip exfiltration", 
    Hint:"Receiving \"successful login\" notifications for a past password on an old account.", 
    js_path:"./levels/advanced_hard/l31.js", 
    category:"advanced_hard", 
    from_and_to:"credential replay with extrafiltration", 
    level_text:null, 
    correct_option:null, 
    neutral_option:null, 
    wrong_option:null, 
    template_type:"browser + message" 
  }, 
  { id:37, 
    Level_no:"l32", 
    page_title:"Multi-vector,adaptive BEC with reconnaissance", 
    Hint:"The emails show an intimate, evolving knowledge of your current work.", 
    js_path:"./levels/advanced_hard/l32.js", 
    category:"advanced_hard", 
    from_and_to:"Fake reconn to reciever", 
    level_text:null, 
    correct_option:null, 
    neutral_option:null, 
    wrong_option:null, 
    template_type:"browser + mail + message" 
  }, 
  { id:38, 
    Level_no:"bl6", 
    page_title:"HoneyBee", 
    Hint:null, 
    js_path:"./levels/advanced_hard/bl6.js", 
    category:"advanced_hard", 
    from_and_to:"Facts of honeybee and Technology", 
    level_text:null, 
    correct_option:null, 
    neutral_option:null, 
    wrong_option:null, 
    template_type:"image" 
  }, 
  { id:39, 
    Level_no:"f", 
    page_title:"Advanced Persistent Phishing", 
    Hint:"Sender is a compromised internal account.", 
    js_path:"./levels/final/f.js", 
    category:"final", 
    from_and_to:"Fake redirection to the user", 
    level_text:null, 
    correct_option:null, 
    neutral_option:null, 
    wrong_option:null, 
    template_type:"mail + Browser+message+notification" 
  }
];
